---
galaxy_info:
  author: Adrian Ursu
  description: Role to setup webupd8 apt repo at launchpad.net.
  company:
  license: BSD
  min_ansible_version: 1.8.4
  platforms:
  - name: Debian
    versions:
    - jessie
    - wheezy
  - name: Ubuntu
    versions:
    - vivid
    - trusty
    - precise
  categories:
  - packaging
  - system
dependencies: []
